# Generated by Django 5.2.4 on 2025-07-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, help_text='Problem constraints'),
        ),
        migrations.AddField(
            model_name='problem',
            name='function_name',
            field=models.CharField(default='solve', help_text='Function name for the solution', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='return_type',
            field=models.CharField(default='int', help_text='Return type of the function', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='template_c',
            field=models.TextField(blank=True, help_text='C code template'),
        ),
        migrations.AddField(
            model_name='problem',
            name='template_cpp',
            field=models.TextField(blank=True, help_text='C++ code template'),
        ),
        migrations.AddField(
            model_name='problem',
            name='template_java',
            field=models.TextField(blank=True, help_text='Java code template'),
        ),
        migrations.AddField(
            model_name='problem',
            name='template_python',
            field=models.TextField(blank=True, help_text='Python code template'),
        ),
    ]
