# Generated by Django 5.2.4 on 2025-08-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_problem_constraints_problem_function_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="testcase",
            options={},
        ),
        migrations.RemoveField(
            model_name="problem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="template_c",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="template_cpp",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="template_java",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="template_python",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="problem",
            name="parameters",
            field=models.CharField(
                blank=True,
                help_text="e.g., x: int or nums: List[int], target: int",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="function_name",
            field=models.CharField(
                default="solve", help_text="e.g., isPalindrome", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="return_type",
            field=models.CharField(
                default="int", help_text="e.g., bool or List[int]", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="is_sample",
            field=models.BooleanField(
                default=False, help_text="Is this a sample test case visible to users?"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testcase_set",
                to="problems.problem",
            ),
        ),
    ]
