# Generated by Django 5.2.4 on 2025-08-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solved_problems_count", models.IntegerField(default=0)),
                ("total_submissions", models.IntegerField(default=0)),
                ("solved_easy_count", models.IntegerField(default=0)),
                ("solved_medium_count", models.IntegerField(default=0)),
                ("solved_hard_count", models.IntegerField(default=0)),
                ("daily_streak", models.IntegerField(default=0)),
                ("last_submission_date", models.DateField(blank=True, null=True)),
                (
                    "bio",
                    models.TextField(blank=True, help_text="User bio", max_length=500),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="User location", max_length=100
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="User website")),
                (
                    "github_username",
                    models.CharField(
                        blank=True, help_text="GitHub username", max_length=50
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        help_text="Preferred programming language",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
