# Generated by Django 5.2.4 on 2025-07-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, help_text="User bio", max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(
                blank=True, help_text="GitHub username", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="User location", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                blank=True, help_text="Preferred programming language", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, help_text="User website"),
        ),
    ]
