[phases.setup]
nixPkgs = ['python311', 'gcc', 'g++', 'openjdk11']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput --clear']

[start]
cmd = 'python manage.py migrate --noinput && gunicorn online_judge_project.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300'
