# Generated by Django 5.2.4 on 2025-07-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test_cases_passed',
            field=models.IntegerField(default=0, help_text='Number of test cases passed'),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_cases_total',
            field=models.IntegerField(default=0, help_text='Total number of test cases'),
        ),
    ]
