# Generated by Django 5.2.4 on 2025-07-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_submission_test_cases_passed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="judged_at",
            field=models.DateTimeField(
                blank=True, help_text="When the submission was judged", null=True
            ),
        ),
    ]
